content/02.body.md
Hi! I am adding this lorem ipsum because it provides us with a form to visualize a bit how text can be added. I confirm that I also added a citation to the text (in the format of a DOI).
This is our first mock pull request, and it tests how Manubot acts when there is one.
=> Adding lorem ipsum filler to the first topics of the introduction and the discussion 

content/02.body.md
Hi, everyone. I would like to add to this text.
=> Added hello to the text.

content/02.introduction.md
This pull request follows the recommendation from @katherinehebert , who suggested the inclusion of a paragraph containing Harry Potter lorem ipsum. I added the citations to the lines, but they should be verified.
=> Adding lorem ipsum to take screenshots to add to the guidelines.

content/01.abstract.md
first pull request for testing
=> first pull request for just testing whether it works or not

README.md
I made two updates to the README file for our manuscript repository including:
1. Updating the heading of the readme with the working title for our manuscript
2. Added the motivation/goal of our paper based on notes I transferred over from our hackmd document.
=> updated title and motivation for paper

content/metadata.yaml
Following suggested guidelines for contributing to the manuscript, adding my author information.
=> Added author information for Brandon PM Edwards

content/02.introduction.md, content/03.use-cases-a.md, content/04.use-cases-b.md, content/05.use-cases-c.md, content/06.discussion-a.md, content/07.conclusion.md, content/08.statements.md, content/09.delete-me.md
In this PR I moved some content from our outline on hackmd over to the manuscript. I moved content for intro, use case section, and discussion.
I also renumbered the remaining files so the manuscript stayed in order.
=> Moving some outline content to manuscript

content/02.introduction.md
I gave a try at both **drafting up a first paragraph** to the manuscript as well as **adding in citations** (which are linked to our discussion board) also in the first paragraph.
=> worked on first paragraph, added citations

content/02.introduction.md
For this PR:
- moved a sentence from the 2nd paragraph up to the first paragraph. 
- Along with moving that sentence, I added a citation for Lowndes 2017 to the first paragraph as well.
- I drafted a 2nd paragraph that summarizes previous research/reviews on GitHub
=> moved one sentence up to first paragraph, drafted second paragraph

content/02.introduction.md
This PR focuses on a few small edits to the intro:
- Deletes the remaining paragraph of stock text since I think we have enough examples of how to format paragraphs/references in our own writing.
- Fixes spacing so it's easier to see where to indicate different contributors to each paragraph.
=> Deleted last intro paragraph of stock text and fixed spacing

content/02.introduction.md, content/04.use-cases-b.md
In this PR I mainly added content and citations to a paragraph about making code citable through archiving GitHub content on figshare or zenodo. 
I also made a few minor formatting changes to this section.
=> Draft of paragraph about using GitHub to make code citable

content/05.use-cases-c.md
I added several sentences about using GitHub to manage data standard documentation to the use-case-c file.
=> Added sentences to misc use cases

content/05.use-cases-c.md
I based myself off the original content and examples from the Hackathon (SORTEE-Hackathon-Dynamic-Collaboration/docs/dynamic_collaboration_material.html) and the notes from our discussions since then.
=> Add a few small paragraphs about GitHub organisations and their applications in EcoEvo

content/03.use-cases-a.md
Adding text to ### Storing and archiving version-controlled data
=> Adding text to ### Storing and archiving version-controlled data

content/06.discussion-a.md
Copied from the "Figure_brainstorming_v2 (6th slide)" to recall what we have done.
Will be improved.
=> Fresh start to write the tips section.

content/02.introduction.md, content/06.discussion-a.md
Addition of some ideas to Tips&Tricks
=> Addition some ideas to Tips&Tricks

content/metadata.yaml
=> Test after system conflict-

content/04.use-cases-b.md
Added some language to "project management" and "collaborative coding" sections
=> Update use cases

content/02.introduction.md
Provided edits to several paragraphs in the introduction and tagged co-authors who are working on the different sections for review.
I also added a lot of new text to section "What's missing about GitHub in EcoEvo / our objective"
=> reviewed introduction and added text to final paragraph

content/06.discussion-a.md
=> Adding tips

content/06.discussion-a.md
In this PR I added text to the first two paragraphs of the discussion which describe 1) a summary/potential impact of using GitHub in EEB and 2) limitations of GitHub for collaboration.
=> added two new paragraphs to discussion

content/06.discussion-a.md
Why aren't more EEB researchers using GitHub
Some changes just to double-check it received well...
=> Why aren't more EEB researchers using GitHub

content/01.abstract.md, content/07.conclusion.md, content/08.statements.md
In this PR, I created a first draft of the conclusion for our paper. I also made two minor additions to other files:
- Removed the 'importance' section from our manuscript since we don't need this for submitting our paper
- Added my funders
=> Draft of conclusion paragraph

content/02.introduction.md, content/06.discussion-a.md
Adding definition of "merge", and adding content to the discussion
=> Work on definitions and discusssion

content/06.discussion-a.md
Added to why aren't more EEB researchers using GitHub - may need to come back and add some citations
=> Clean up and expand why eeb hasn't used github

content/02.introduction.md, content/04.use-cases-b.md, content/06.discussion-a.md
Some deletions and additions to Tips, Uses Cases (Part C) and Intro
=> Some deletions and additions to Tips, Uses Cases (Part C) and Intro

content/02.introduction.md
Hi, all!
I am adding here a series of changes restructuring and modifying the content of the introduction. Detailed changes are included in the description of the commits associated with this pull request. 
In summary, the major changes to the structure and to the content were: 
- I added a new first paragraph providing the context of how researchers in ecology and evolution have adopted code as part of their research process, and that with this, an efficient workflow facilitating the collaboration, use and documentation of scientific code becoming fundamental.  I justify this because I felt that it would be beneficial for the introduction of our manuscript to adopt a bit broader context, instead of focusing only on the advantages of adopting GitHub;
- I shifted the content of the …
=> Modifications to the structure and the content of the introduction 

content/01.abstract.md
Hi, all.
This pull request adds a broader context to the first sentences of the abstract and mentions that EEB researchers have been critically dependent on scientific code, which requires efficient forms for collaborating and sharing code and then introduces GitHub. 
Other minor changes were merging a few sentences and reducing others.
Please let me know if you have any recommendations!
=> Modifications to the abstract

content/03.use-cases-a.md
Hi @emmajhudgins and @colebrookson I went through your sections of the intro today and just had a few modifications to review.
@emmajhudgins I created issue #143 to indicate that we need to add a definition for releases to Box1
=> edits to use cases section a

content/02.introduction.md
In this PR, I did a read through the entire intro making suggestions for edits to the text, adding in a few citations and making small edits to Box 1.
=> Edits throughout introduction

content/07.conclusion.md
Just made a few minor edits to conclusion paragraph and updated figure numbers.
=> edits to conclusion

README.md, content/01.abstract.md, content/02.introduction.md, content/03.use-cases-a.md, content/04.use-cases-b.md, content/05.use-cases-c.md
Just made a quick update to our manuscript title and fixed a few typos.
=> updated title and made some spelling updates

content/06.discussion-a.md
In this PR I read through and made detailed updates to discussion.  There was a 2nd section (still in outline form) related to limitations that I combined with an earlier paragraph already on limitations so hopefully that works for everyone!
@emmajhudgins there we some comments on Box 1 (maybe should be renamed to box 2 now that I'm thinking of it) that were left in hypothesis. I made a couple of changes to the content there, but added my own comment for you to check out in hypothesis.
=> edits to discussion

editorial-communication/cover-letter-submission.Rmd
Thanks @DrMattG for the great suggestions to the cover letter. Eventually, this will close #173. Please let me know what you think and if I should make other updates in this PR.
=> edited cover letter

content/04.use-cases-b.md
I wanted to address the comment in hypothesis in relation to the paragraph on licensing options (line 56). I also picked up a few typos from the other parts of this section
=> Editing 04.use-cases-b.md

content/02.introduction.md
Renamed box 1 as @Aariq suggested and also tried to provide reference to box 1 in intro text.
=> renamed box 1 for easier reference

content/03.use-cases-a.md, editorial-communication/cover-letter-submission.Rmd
A few minor suggestions for the cover letter and suggestions for 'Storing a research compendium'.
=> Helen edits

README.md, content/metadata.yaml
In this PR I made a few quick adjustments to authorship order, affiliations and names based on comments in hypothesis as well as our email thread on authorship.
Also, adjusted title of manuscript based on @dylangomes suggestion!
=> updated authorship order and manuscript title

content/02.introduction.md
Responding to comments in hypothesis on the Intro.
=> Incorporate comments from hypothesis in Intro

content/01.abstract.md
Response to changes highlighted in the Abstract in the full group edits in hypothesis
=> Abstract changes from hypothesis

editorial-communication/cover-letter-submission.Rmd
Hi, 
I made a few modifications to the cover letter to remove the acronyms (which did not appear essential and could bother the editorial) and suggested some changes to the content.
=> Removing acronyms from the cover letter and making a few modifications

content/08.statements.md
Adding author contribution statement, and acknowledgement
=> added author credit statements

editorial-communication/cover-letter-submission.Rmd
@shafieisabets for some reason your PR issued a manubot error. I am going to close that PR, and instead include your suggestion in this PR.
=> incorporating changes to cover letter

content/05.use-cases-c.md
Hi, again
I have decreased the length of this section and elaborated on the context of backwards / version compatibility along with the automation that runners on GitHub Actions provide.
Please do not hesitate to let me know if there are issues or other suggestions here.
=> Decreasing the length of the text and improving consistency of the narrative: `03.use-cases-c.md`

content/06.discussion-a.md, content/07.conclusion.md
In this PR I made some edits to discussion section to make it a bit more concise and fixed some links.
Minor edits to wording in the conclusion.
=> edits to discussion and conclusion

content/01.abstract.md
as suggested by @fhillemann: see this [issue](https://github.com/SORTEE-Github-Hackathon/manuscript/issues/253)
=> Abstract changes

content/02.introduction.md, content/03.use-cases-a.md, content/07.conclusion.md
Hi everyone! 👋🏻  
Thanks @pedrohbraga for making some great updates to the manuscript. I just did a full read-through and am requesting a PR review before submitting to MEE. Thanks!
=> Minor changes to wording

content/02.introduction.md
Worked on the intro a bit here just to reduce jargon in a few paragraphs.
=> reducing jargon in intro

content/06.discussion-a.md
Adds 2 sentences to disucssion citing Dylan et al's paper and emphasizing why code should be shared and version controlled even if future use is unclear. Closes #289
=> Edits addressing E1.3
